spring:
  datasource:
    url: jdbc:mysql://112.74.41.106:3306/todo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: todo_user
    password: MyPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

logging:
  level:
    com.todolist: DEBUG
    org.springframework.web: DEBUG

# Swagger 3 配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
  show-actuator: true

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000  # 24小时（毫秒）